from config import GameOptions

configurable_options = GameOptions()
ASTEROID_KINDS = configurable_options.ASTEROID_KINDS
# Screen & Misc Constants
LINE_WIDTH = 2
STAR_MAX_RADIUS = 3

# Player Constants
PLAYER_LENGTH = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 300
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
SHOT_RADIUS = 5

# Asteroid Constants
ASTEROID_MIN_RADIUS = 20
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_ROTATION_SPEED = 300
