from config import GameOptions

configurable_options = GameOptions()
ASTEROID_KINDS = configurable_options.ASTEROID_KINDS
# Screen & Misc Constants
#SCREEN_WIDTH = 1280
#SCREEN_HEIGHT = 720
LINE_WIDTH = 2
STAR_MAX_RADIUS = 3

# Player Constants
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 300
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
#PLAYER_MAX_BULLETS_ON_SCREEN = 5
SHOT_RADIUS = 5

# Asteroid Constants
ASTEROID_MIN_RADIUS = 20
#ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
#ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MAX_ROTATION_SPEED = 300
#MAX_ASTEROIDS_ON_SCREEN = 15
